Unit Testing for querying Larders: Initialize
The set-up function HAS to be called "setUp(self)". This name is FIXED. It CANNOT be re-named to something like "setUpTestData(sef)". If you do such a re-naming, you get an error:
TypeError: setUpTestData() missing 1 required positional argument: 'self'